version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:ml-service-1
    container_name: ml-service_container
    command: python manage.py runserver 0.0.0.0:8000